spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      properties:
        spring.json.add.type.headers: false
